spring:
  profiles:
    active: local
    group:
      local: local
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
jwt:
  header: Authorization
  secret: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
  token-validity-in-seconds: 3600000